import curses

def get_input_ints(func):
    def wrapper(*args,**kwargs):
        while True:
            ''' Implement try-except to catch non-numbers and non-positive numbers'''
            try:
                (x,y) = func(*args,**kwargs)
                if (x,y) > (0, 0):
                    break
            except:
                print('\nPlease enter a positive number!\n')
                pass
        return (x,y)
    return wrapper

int_input = lambda x: int(input(x))

@get_input_ints
def get_params(str1, str2, int_input = int_input):
    return map(int_input, [str1,str2])

(WINDOW_HEIGHT, WINDOW_WIDTH), (X_INIT, Y_INIT) = map(get_params,
                       ('Please enter the window height for the snake game:\n',
                                    'Please enter the starting x position:\n'),
                       ('Please enter the window width for the snake game:\n',
                                   'Please enter the starting y position:\n'))


def setup_window(WINDOW_HEIGHT = WINDOW_HEIGHT, WINDOW_WIDTH = WINDOW_WIDTH):

    ''' Check documentation for these functions'''

    # Initialize the library.
    curses.initscr()
    # Don't echo commands on screen.
    curses.noecho()
    # Set cursor visible.
    curses.curs_set(1)

    # Return a new window, whose left-upper corner is at (0,0), and whose height/width is WINDOW_HEIGHT,WONDOW_WIDTH
    W = curses.newwin(WINDOW_HEIGHT,WINDOW_WIDTH)
    W.border(0)
    # If yes is 1, escape sequences generated by some keys (keypad, function keys) will be interpreted by curses.
    W.keypad(1)

    return W
